version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-lab-app:latest
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      # PORT: 5000  # optional - your app.py currently uses a fixed port
    restart: unless-stopped